import Head from 'next/head';
import React from 'react';

function About(): JSX.Element {
    return (
        <div>
            <Head>
                <title>Trey Hollins - About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="w-full h-screen">
                    
                </div>
            </main>
        </div>
    );
}

export default About;
