import Head from 'next/head';
import React from 'react';
import AboutComponent from '../components/AboutComponent';

function About(): JSX.Element {
    return (
        <div>
            <Head>
                <title>Trey Hollins - About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <AboutComponent />
            </main>
        </div>
    );
}

export default About;
