import Head from 'next/head';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Trey Hollins - Developer Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Hero />
            </main>
            <Footer />
        </div>
    );
}
