import Head from 'next/head';
import Hero from '../components/Hero';
import LatestCode from '../components/LatestCode';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Trey Hollins - Developer Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Hero />
                <LatestCode />
            </main>
        </div>
    );
}

